baseURL: 'http://rohankataria.com/'
languageCode: 'en-us'
title: 'Rohan Kataria'
theme: "PaperMod"

params:
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: "Welcome to my blog about... Data Engineering"

    socialIcons:
        - name: "Linkedin"
          url: "https://linkedin.com/in/imrohan"
        - name: "other"
          url: "https://calendly.com/imrohankataria/30min"
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
