baseURL: 'http://rohankataria.com/'
languageCode: 'en-us'
title: 'Rohan Kataria'
theme: "PaperMod"


languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Calendly
                  url: https://calendly.com/imrohankataria/30min

                  
params:
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: "Welcome to my blog about... Data Engineering"

    socialIcons:
        - name: "Linkedin"
          url: "https://linkedin.com/in/imrohan"

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
