baseURL: 'http://rohankataria.com/'
languageCode: 'en-us'
title: '@Rohan's Blog'
theme: "PaperMod"


languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Calendly
                  url: https://calendly.com/imrohankataria/30min

                  
params:
    homeInfoParams:
        Title: "Rohan Kataria"
        Content: "Welcome to my blog about... Data Engineering
        I'm a skilled data engineer specializing in Data Migration, Architecting Data Platforms & BI.
        My industry experience spans energy, healthcare, manufacturing, and human resources."

    socialIcons:
        - name: "Linkedin"
          url: "https://linkedin.com/in/imrohan"

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
